import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
const Navigation = () => {
    var _a, _b;
    const { user, isAuthenticated, logout } = useAuth();
    const navigate = useNavigate();
    const handleLogout = () => {
        logout();
        navigate('/login');
    };
    return (_jsx("nav", { className: "bg-white shadow-lg", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Link, { to: "/", className: "flex-shrink-0 flex items-center", children: _jsx("h1", { className: "text-xl font-bold text-indigo-600", children: "RecruitHub" }) }), _jsxs("div", { className: "hidden md:ml-6 md:flex md:space-x-8", children: [_jsx(Link, { to: "/jobs", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "Browse Jobs" }), isAuthenticated && (user === null || user === void 0 ? void 0 : user.role) === 'employer' && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "Dashboard" }), _jsx(Link, { to: "/dashboard/create", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "Post Job" })] })), isAuthenticated && (user === null || user === void 0 ? void 0 : user.role) === 'candidate' && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/candidate/profile", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "Profile" }), _jsx(Link, { to: "/candidate/applications", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "My Applications" })] }))] })] }), _jsx("div", { className: "flex items-center", children: isAuthenticated ? (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("span", { className: "text-sm text-gray-700", children: ["Welcome, ", ((_a = user === null || user === void 0 ? void 0 : user.candidate) === null || _a === void 0 ? void 0 : _a.firstName) || ((_b = user === null || user === void 0 ? void 0 : user.company) === null || _b === void 0 ? void 0 : _b.name) || (user === null || user === void 0 ? void 0 : user.email)] }), _jsx("button", { onClick: handleLogout, className: "bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md text-sm font-medium", children: "Logout" })] })) : (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(Link, { to: "/login", className: "text-gray-900 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium", children: "Sign In" }), _jsx(Link, { to: "/register", className: "bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md text-sm font-medium", children: "Sign Up" })] })) })] }) }) }));
};
export default Navigation;
